<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<Nullable>enable</Nullable>
		<Version>1.1.0-stream.1</Version>
		<Authors>ErenKrt</Authors>
		<PackageProjectUrl>https://github.com/ErenKrt/TlsClient.NET</PackageProjectUrl>
		<Description>Shared models and helpers for TlsClient.NET.</Description>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.Text.Json" Version="9.0.8" />
	</ItemGroup>
</Project>