name: Check tls-client version

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-tls-client-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Get latest release info
      id: get_latest
      run: |
        RELEASE_JSON=$(curl -s https://api.github.com/repos/bogdanfinn/tls-client/releases/latest)
        TAG_NAME=$(echo "$RELEASE_JSON" | jq -r '.tag_name')
        echo "Latest tag: $TAG_NAME"
        echo "LATEST_TAG=$TAG_NAME" >> $GITHUB_ENV

    - name: Check if new version
      id: check_version
      run: |
        if [ -f "./tls-client-version.txt" ]; then
          LAST_VERSION=$(cat ./tls-client-version.txt)
        else
          LAST_VERSION=""
        fi

        echo "Last processed version: $LAST_VERSION"

        if [ "$LAST_VERSION" = "${{ env.LATEST_TAG }}" ]; then
          echo "Already up to date. Exiting."
          echo "SHOULD_CONTINUE=false" >> $GITHUB_ENV
        else
          echo "New version found: ${{ env.LATEST_TAG }}"
          echo "SHOULD_CONTINUE=true" >> $GITHUB_ENV
        fi

    - name: Exit if no update
      if: env.SHOULD_CONTINUE == 'false'
      run: exit 0

    - name: Update version file
      run: |
        echo "${{ env.LATEST_TAG }}" > tls-client-version.txt
        echo "Updated version file to ${{ env.LATEST_TAG }}"

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add tls-client-version.txt
        git commit -m "Update tls-client version to ${{ env.LATEST_TAG }}"
        git push